name: Book

on:
  push:
    branches:
      - master

jobs:
  book:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install mdbook fork via cargo
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git install --git https://github.com/barsoosayque/mdBook.git --no-default-features --features search mdbook 

      - name: Build book
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/
